# Generated by Django 5.1.2 on 2024-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
    ]
