# Generated by Django 5.1.2 on 2024-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_gallery_alter_about_image_alter_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='barbers/')),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(),
        ),
    ]
